// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbFc1_BkEVQBEScs18atcDEQegbIn3qJc',
    appId: '1:659735339001:web:df830e93beafc8d592e728',
    messagingSenderId: '659735339001',
    projectId: 'fcmflutter12',
    authDomain: 'fcmflutter12.firebaseapp.com',
    storageBucket: 'fcmflutter12.appspot.com',
    measurementId: 'G-DN1LZJNC9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvEkAgcpT1Wohx9__5OqmwmSHJPXZY3Ig',
    appId: '1:659735339001:android:96d723aa9efe494e92e728',
    messagingSenderId: '659735339001',
    projectId: 'fcmflutter12',
    storageBucket: 'fcmflutter12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTUfgWNGY_JLI2e-LR2yFS5jn-EYacvO4',
    appId: '1:659735339001:ios:120ae7270ca050ed92e728',
    messagingSenderId: '659735339001',
    projectId: 'fcmflutter12',
    storageBucket: 'fcmflutter12.appspot.com',
    iosClientId: '659735339001-5c6c5ffnqr9qk82mj3ef1u2reb4uh01b.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTUfgWNGY_JLI2e-LR2yFS5jn-EYacvO4',
    appId: '1:659735339001:ios:ab7df7a4fcecaf9792e728',
    messagingSenderId: '659735339001',
    projectId: 'fcmflutter12',
    storageBucket: 'fcmflutter12.appspot.com',
    iosClientId: '659735339001-jhpme4teh8c6o71p0v3mdtr2j2b6o68t.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmflutter.RunnerTests',
  );
}
